trying to detect changes to height using mutation observer - getting Uncaught TypeError: MutationObserver.observe: Argument 1 does not implement interface Node.